### ISSUE TITLE
[Update] compatibility with future Typo3 versions (8 LTS, 9 LTS, ..)

### ISSUE THREAD

**Issue by medarob** [portrino/shopware-typo3-connector#1]
Hi,

Are there any plans in supporting Typo3 8 LTS and later this year Typo3 9 LTS ?

Thank you very much.

**Comment by EvilBMP** [comment]
Sorry for the late reply, but this is the Shopware plugin and not the TYPO3 extension. Please have a look at the corresponding TYPO3 extension repository https://github.com/portrino/px_shopware 

The TYPO3 extension is compatible up to 8 LTS. When the release of 9 LTS is near, we will surely update the extension accordingly.

Regards
