### ISSUE TITLE
Version check breaks with Shopware 5.6

### ISSUE THREAD

**Issue by jonakieling** [portrino/shopware-typo3-connector#4]
Hey,

within the ApiUrlDecorator there is a check for the contents of \Shopware::VERSION since it has been deprecated in the past. Now with Shopware 5.6 this constant is removed and the code below breaks:
```
if (\Shopware::VERSION !== '___VERSION___') {
    $currentVersion = \Shopware::VERSION;
}
```
A simple `defined('\Shopware::VERSION')` in front fixes this. PR is here https://github.com/portrino/shopware-typo3-connector/pull/3

Kind regards
Jona

**Comment by EvilBMP** [comment]
Sorry, had to merge the PR manually - but you are mentioned in the release notes :-) Thx 👍
