### ISSUE TITLE
how to check portrino / shopware-typo3-connector is compactible for shopware6

### ISSUE THREAD

**Issue by anumolkmani** [portrino/shopware-typo3-connector#5]

**Comment by EvilBMP** [comment]
It isn't/ cannot be compatible because Shopware 6 has a completely different codebase compared to Shopware 5.

And right now there is no Shopware 6 compatible version of this plugin available/ in development.

**Comment by anumolkmani** [comment]
Okay.Is there any other possibile ways to connect shopware 6 with typo3
